### ISSUE TITLE
[Not an issue] More info about protocol :)

### ISSUE THREAD

**Issue by iordic** [jcheger/fnirsi-dc580-protocol#1]
Hi! I've created a repo with a Java GUI for this device and I've reversed the FNIRSI software too and created a Java GUI for the device. I've searched at GitHub for similar repositories and found yours. I've written all the details I've seen of the comunication in the [wiki](https://github.com/iordic/jdcx/wiki/Serial-communication) of the project if you want to see it :)
Cheers!

**Comment by jcheger** [comment]
Nice job. Thanks for sharing.
I did put a link to your project in the README.

**Comment by iordic** [comment]
Thanks! I'll do the same <3
